name: Build
on:
  push:
    branches:
      - changelog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 1466587594/get-current-time@v2
        id: current-time
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: dist
          path: dist
      - name: Clean
        working-directory: ./dist
        run: |
          git rm -rf .
          git clean -fxd
      - name: Build
        run: |
          npm install
          npm run all
          cp action.yml dist/action.yml
      - name: Release
        working-directory: ./dist
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . --force
          git commit --allow-empty -m "Update ${{ steps.current-time.outputs.time }}"
          git tag -f -a -m "Update ${{ steps.current-time.outputs.time }}" v1
          git push
          git push --tags -f
